name: Test
on:
  workflow_dispatch:

jobs:
  endpoints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
    - name: check
      run: |
        echo "Testing DNS:"
        dig dot-rpc.stakeworld.io
        curl https://dot-rpc.stakeworld.io
